# Generated by Django 4.2.7 on 2023-11-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_bidding_time_comments_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_highest_bid_amount',
            new_name='current_highest_bid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='starting_bid_amount',
            new_name='starting_bid',
        ),
    ]
