# Generated by Django 4.2.7 on 2023-11-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_current_highest_bid_amount_product_current_highest_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_market',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_highest_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
