# Generated by Django 4.2.7 on 2023-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_product_on_market_alter_product_current_highest_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_highest_bid',
        ),
        migrations.AddField(
            model_name='product',
            name='bids',
            field=models.ManyToManyField(related_name='products', to='auctions.bids'),
        ),
    ]
